language: python

cache: pip

matrix:
    include:
        - os: linux
          python: 2.7
          env: TOXENV=py27

        - os: linux
          python: 3.5
          env: TOXENV=py35

        - os: linux
          python: 3.6
          env: TOXENV=py36

        - os: linux
          python: 3.7
          env: TOXENV=py37

        - os: linux
          python: 3.8
          env: TOXENV=py38

        - os: linux
          python: 3.6
          env: TOXENV=cov
          after_success:
              - travis_retry pip install pytest-cov coveralls --upgrade
              - python setup.py test --addopts "-v --cov dataproperty --cov-report term-missing"
              - coveralls

        - os: osx
          language: generic
          env: TOXENV=py36

install:
    - travis_retry bash -x .travis/install.sh

script:
    - bash -x .travis/run_test.sh

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/39fa22b3bc5ab82281a2
        on_success: change # options: [always|never|change] default: always
        on_failure: always # options: [always|never|change] default: always
        on_start: never # options: [always|never|change] default: always
    slack:
        secure: tnsOg+UxjwHhV0coUdMNMeKk91vtW5scYB89qGotGJBp7lMPhPagmS7I4ICFcgyNmLNpbPmlKaz0e93TPYg5RoEzwrmQx4mn7wrg/GT8omtdxhSZlMt9og70uqCwVILv63pT+gpj5/yDpGCm7IOVA1+exWbFYCH1uOqHhRgAVLU1hXN9tET8LjU0gyEuGCkoz5/NkQhjAkf1Z+SDecZ0SFDz5MHbgbfQ+pK4LbQLd1YduC56R6PpvwuFcxGxVydwQvxy0/cR7qYBRdEMY0dZsUHUm+9nlucqhr2lylkcTy77+LwPSkjXJvw4sQzFgaFB8OXWhV/5dNSDdoYmrTpv9VEwDbDTkKOR47Rnwyvo4SCXEET3oClEsQgoq5Xh5rOR51mCW0RiJfDktB0pabLVH490QkjawU6cjtliSueXym+OhDMBNC/y6paXSpChQeUVTKj/Z/zCoc/cHzQr9LX9CY5RS1IrEGWMF3EOIQ73V9GhPrrX9U9B65HLz3KxgDJF18Xbiul0+OM5yEHUOOZQWJYPPY+1u4SZP58AjYZa4l1ZXQHayivaDCcovY0nxHDnM+oTHh+xnv3J/b6VYoMdy1ZF9kQhfiDV02UYIF7G3dHO/RkpQ7xYzEX4Ik73ZTlV5CbZyiJq+UUQZFNV1XhYF4mVQDgory+MVj4GP0sIyoA=
